# Generated by Django 3.2.15 on 2022-08-30 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='use',
            field=models.CharField(choices=[('games', 'Games'), ('books', 'Books'), ('events', 'Events')], default='games', max_length=254, verbose_name='Use'),
        ),
    ]
