# Generated by Django 3.2.15 on 2022-08-30 20:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tags', '0002_tag_use'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=254, verbose_name='Name')),
                ('type', models.CharField(choices=[('concert', 'Concert'), ('conference', 'Conference')], default='concert', max_length=254, verbose_name='Type')),
                ('location', models.CharField(max_length=254, verbose_name='Location')),
                ('notes', models.CharField(blank=True, max_length=1024, verbose_name='Notes')),
                ('tags', models.ManyToManyField(blank=True, limit_choices_to={'use': 'events'}, related_name='events', to='tags.Tag', verbose_name='Tags')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
            },
        ),
    ]
