# Generated by Django 3.2.15 on 2022-08-30 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0002_tag_use'),
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='tags',
            field=models.ManyToManyField(blank=True, limit_choices_to={'use': 'games'}, related_name='games', to='tags.Tag', verbose_name='Tags'),
        ),
    ]
